### ISSUE TITLE
Contact form 

### ISSUE THREAD

**Issue by ArQuel** [tbakerx/react-resume-template#12] opened 2019-06-09 18:51 UTC
First of all, Thanks for your awesome great work!!!

Can u help me to send the value of forms in my mailbox ? Or if u have a better idea to work with this form ? Thanks a lot !! 

NB: When I send the forms, there is infinite img and nothing behind to confirm this is sent or where

sorry for my english

ArQuel

**Comment by jm-evealed** [comment] 2020-07-28 00:14
I am having the same issue. The contact form goes nowhere.

**Comment by vicgwee** [comment] 2021-10-13 06:04
Duplicate of #5

**Comment by tbakerx** [comment] 2022-09-10 15:02
My sincere apologies for the inactivity on this project. I've been hard at work at my full-time role and haven't had much time to devote to my open source work. I have however, just released v2 of this project which will likely have resolved any current issues. 

I will be closing all open issues at this time, if your issue persists into the current version please kindly re-open it and I will do my best to address them. Thank you for using the project!

**Closed as completed by tbakerx** 2022-09-10 15:02 UTC
